fix: update lxd dependency
project-stacker/stacker pull request #389
Opened 2023-01-10 18:04 UTC by hallyn

Update lxd to one including:

commit 599dd2280553f816b945ebf5a128a6fc690a5219
Author: Andreas Dilger <adilger@whamcloud.com>
Date:   Fri Jan 7 12:50:05 2022 -0700

    shared/util/linux: only complain on xattr size increase

As otherwise reading xattrs on overlay can break.

Signed-off-by: Serge Hallyn <serge@hallyn.com>

**What type of PR is this?**

**Which issue does this PR fix**:

**What does this PR do / Why do we need it**:

**If an issue # is not available please add repro steps and logs showing the issue**:

**Testing done on this change**:

**Automation added to e2e**:

**Will this break upgrades or downgrades?**

**Does this PR introduce any user-facing change?**:

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-01-10 18:21 UTC, smoser requested changes
I think you're intending that this 'Fixes #388', right?

You should put that in the commit message.

2023-01-10 21:27 UTC, hallyn commented
> I think you're intending that this 'Fixes #388', right?
> 
> You should put that in the commit message.

Hm, no, I don't think that's related.

This is the fix for overlay's listxattr(path, NULL, 0) returning a larger size estimate than the actual size returned when you pass a buffer with listxattr(path, buf, sz).  When you pass a non-zero sz (and a buffer), then overlay filters out some xattrs.  When only telling you the size, it doesn't filter those out, so the size you're told to allocate can be more than what you really need.  We shouldn't fail when that happens.

2023-01-11 16:00 UTC, smoser commented
> > I think you're intending that this 'Fixes #388', right?
> > You should put that in the commit message.
> 
> Hm, no, I don't think that's related.
> 
> This is the fix for overlay's listxattr(path, NULL, 0) returning a larger size estimate than the actual size returned when you pass a buffer with listxattr(path, buf, sz). When you pass a non-zero sz (and a buffer), then overlay filters out some xattrs. When only telling you the size, it doesn't filter those out, so the size you're told to allocate can be more than what you really need. We shouldn't fail when that happens.

oh, sorry then. i guess the timing of this after my open of #388 made me think that newer lxc would dtrt with that ',userxattr'. and the commit message even inculded 'xattr'.  just bad luck. sorry for the noise.

2023-01-20 00:36 UTC, hallyn commented
Ok wel lthis is also folded into #391 so i'll close this

2023-01-20 00:36 UTC, closed without merging