feat(erofs): initial commit for erofs support
project-stacker/stacker pull request #626
Opened 2024-06-14 05:08 UTC by rchincha

Fixes https://github.com/opencontainers/image-spec/issues/1190

**What type of PR is this?**

**Which issue does this PR fix**:

**What does this PR do / Why do we need it**:

**If an issue # is not available please add repro steps and logs showing the issue**:

**Testing done on this change**:

**Automation added to e2e**:

**Will this break upgrades or downgrades?**

**Does this PR introduce any user-facing change?**:

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-06-14 05:41 UTC, hsiangkao commented
Hi @rchincha, I'm currently working on incremental builds and I plan to release erofs-utils v1.8 this month (with multi-threaded mkfs, incremental builds, Intel QPL, etc.), but anyway, I'd suggest use cgo for initial EROFS support (with formal liberofs APIs exported) for now (or even binary integration) since this go implemention seems somewhat incomplete (and maybe even broken.. I don't have enough time to look into that since other prioritied stuffs are on hands..)

2024-06-14 05:57 UTC, rchincha commented
@hsiangkao I suspect that cgo path may be what ends up happening. Currently, just prototyping quickly to understand the interfaces and scope of changes/work.

2024-08-16 08:56 UTC, VPS6123456 approved these changes

2024-09-18 01:41 UTC, hsiangkao commented
One thing I might need to mention here is that `erofs` supports external blobs or chunks since Linux 5.16 compared to Squashfs because Dragonfly Nydus once asked this feature to deduplicate data in chunks among different container images.

I'm not sure if it's worthwhile to highlight this, you could just make a tiny metadata with external blobs (which can be used for multiple images) for reference.
Currently only Nydus has userspace tools to generate chunk blobs, if that is interested in other use cases, I could seek more time to implement this in `mkfs.erofs` too.

2024-11-16 06:10 UTC, rchincha commented
```
$ cat stacker.yaml

build:
  from:
    type: docker
    url: docker://public.ecr.aws/docker/library/busybox:1.37-glibc
```

```
 $ /tmp/stacker  build -layer-type erofs
Creating new OCI Layout at "/data/hdd/rchincha/tmp/lxc/oci"
preparing image build...
imported file hashes (after substitutions):
loading docker://public.ecr.aws/docker/library/busybox:1.37-glibc
Copying blob a46fbb00284b done
Copying config 27a71e19c9 done
Writing manifest to image destination
Storing signatures
mkfs.erofs 1.4                                                                                                                                                                    c_version:           [     1.4]
        c_dbg_lvl:           [       2]
        c_dry_run:           [       0]
filesystem build built successfully
```

2024-11-21 19:38 UTC, rchincha commented
@hsiangkao 

Is there an equivalent of "unsquashfs" in erofs-utils?

https://manpages.debian.org/testing/squashfs-tools/unsquashfs.1.en.html

SYNOPSIS

unsquashfs [OPTIONS] FILESYSTEM [files to extract or exclude (with -excludes) or cat (with -cat )]

2024-11-22 02:34 UTC, hsiangkao commented
Hi!
> @hsiangkao
> 
> Is there an equivalent of "unsquashfs" in erofs-utils?
> 
> https://manpages.debian.org/testing/squashfs-tools/unsquashfs.1.en.html
> 
> SYNOPSIS
> 
> unsquashfs [OPTIONS] FILESYSTEM [files to extract or exclude (with -excludes) or cat (with -cat )]

fsck.erofs --extract=<dir> FILESYSTEM to extract the whole filesystem...

Currently, there is no exclude way but it can be added later.

2024-12-09 03:40 UTC, raharper requested changes

2024-12-09 03:40 UTC, raharper commented on install-build-deps.sh
> +        erofs-utils erofsfuse
one per line

2024-12-09 03:40 UTC, raharper commented on pkg/types/layer_type.go
> +	case squashfs.GenerateSquashfsMediaType(squashfs.GzipCompression):
We already had a case for Squash + Gzip -- was this supposed to be zstd?

2024-12-09 03:40 UTC, raharper commented on pkg/types/layer_type.go
> +	case erofs.GenerateErofsMediaType(erofs.LZ4HCCompression):
These are the same case right? LZ4H , fallthrough?

2024-12-09 03:40 UTC, raharper commented on test/atomfs-erofs.bats
> +    last_layer_hash=$(cat oci/blobs/sha256/$manifest | jq -r .layers[$last_layer].digest | cut -f2 -d:)
just a general comment, prolly worth an issue, but we can avoid the `cat | jq` and just `jq xxx < file`

2024-12-09 03:40 UTC, raharper commented on test/helpers.bash
> +      echo "PRIVILEGE_LEVEL=$PRIVILEGE_LEVEL but empty SUDO_USER"
SUDO_USER or SUDO_UID ? both are present, but your error prints a different ENV value than what is checked.
```suggestion
      echo "PRIVILEGE_LEVEL=$PRIVILEGE_LEVEL but empty SUDO_UID"
```

2024-12-09 03:40 UTC, raharper commented on test/helpers.bash
> +   if [ -z "$SUDO_UID" ]; then
```suggestion
   if [ -z "$SUDO_USER" ]; then
```
which one? SUDO_UID or SUDO_USER?

2025-02-13 07:31 UTC, rchincha commented on install-build-deps.sh
> +        erofs-utils erofsfuse
fixed.

2025-02-13 07:44 UTC, hsiangkao commented
Hi @rchincha, currently azure kernels are somewhat fragmented on kconfig, I've raised issues to ubuntu in order to resolve them, but maybe it still need some time to find proper github runner images in github:
https://bugs.launchpad.net/ubuntu/+source/linux-azure/+bug/2081613
https://bugs.launchpad.net/ubuntu/+source/linux-azure/+bug/2098178

I discussed with ubuntu developpers by email months ago, they suggested: ".. until that lands, you can work around this by installing the `linux-modules-extra-azure` package in your CI runners. "

It may still cause some inconvenience but will fix with the future release linux-azure release versions.

2025-02-17 20:16 UTC, raharper commented on .github/workflows/build.yaml
> +          sudo apt-get install -y linux-modules-extra-$(uname -r)
Please don't add more stuff to build.yaml; instead fix the scripts so that we can recreate this outside of github.

2025-02-17 20:16 UTC, raharper commented on .github/workflows/coverage.yaml
> +          sudo apt-get install -y linux-modules-extra-$(uname -r)
Please add to install build deps.

2025-02-17 20:16 UTC, raharper commented on go.mod
> +	machinerun.io/atomfs => github.com/rchincha/atomfs v0.0.0-20250217174059-a0b78e163e7f
whats in here that's not in tip atomfs?

2025-02-17 20:16 UTC, raharper commented on pkg/types/layer_type.go
> +		return LayerType{Type: lt, Verity: verity}, nil
```suggestion
	case "squashfs", "erofs":
		return LayerType{Type: lt, Verity: verity}, nil
```

2025-02-17 20:40 UTC, rchincha commented on go.mod
> +	machinerun.io/atomfs => github.com/rchincha/atomfs v0.0.0-20250217174059-a0b78e163e7f
https://github.com/project-machine/atomfs/pull/25

make filesystems more pluggable, and all of erofs

2025-02-17 21:42 UTC, raharper commented on .github/workflows/coverage.yaml
> +          sudo apt-get install -y linux-modules-extra-$(uname -r)
I'm confused.  If we need erofs, then it's provided by `linux-modules-6.8.0-53-generic` package;  and it is *not* included in the `linux-modules-extra-$(uname -r)` package, only the directory is present:

```
$ dpkg -L linux-modules-6.8.0-52-generic | grep erofs
/lib/modules/6.8.0-52-generic/kernel/fs/erofs
/lib/modules/6.8.0-52-generic/kernel/fs/erofs/erofs.ko
$ dpkg -L linux-modules-extra-6.8.0-52-generic | grep erofs
/lib/modules/6.8.0-52-generic/kernel/fs/erofs
```

> This is a GH runner thing for Azure linux.

are you saying that coverage runs on something other than Ubuntu?

2025-02-17 22:46 UTC, raharper commented on go.mod
> +	machinerun.io/atomfs => github.com/rchincha/atomfs v0.0.0-20250217174059-a0b78e163e7f
None of the unresolved comments have been addressed in https://github.com/project-machine/atomfs/pull/25

2025-02-18 05:54 UTC, rchincha commented on .github/workflows/coverage.yaml
> +          sudo apt-get install -y linux-modules-extra-$(uname -r)
https://github.com/project-stacker/stacker/pull/626#issuecomment-2655766372

2025-02-18 13:20 UTC, raharper commented on .github/workflows/coverage.yaml
> +          sudo apt-get install -y linux-modules-extra-$(uname -r)
A lot of back and forth can be avoided if the commit message or the code changes include comments about the changes.

I suggest in `install-build-deps.sh`:

```
# cloud kernels, like linux-azure, don't include erofs in the linux-modules package and instead put it linux-modules-extra
if ! modinfo erofs &>/dev/null; then
   sudo apt install linux-modules-extra-$(uname -r)
fi

2025-02-19 06:11 UTC, rchincha commented on pkg/types/layer_type.go
> +	case squashfs.GenerateSquashfsMediaType(squashfs.GzipCompression):
Cleaned up.

2025-02-19 06:12 UTC, rchincha commented on test/atomfs-erofs.bats
> +    last_layer_hash=$(cat oci/blobs/sha256/$manifest | jq -r .layers[$last_layer].digest | cut -f2 -d:)
I also need to parameterize squashfs and erofs tests into a single driver file.
Will punt this cleanup to a different PR.

2025-02-19 06:13 UTC, rchincha commented on test/helpers.bash
> +      echo "PRIVILEGE_LEVEL=$PRIVILEGE_LEVEL but empty SUDO_USER"
hmm...
SUDO_UID is a uid
SUDO_USER is a username

2025-02-19 06:22 UTC, rchincha commented on pkg/types/layer_type.go
> +		return LayerType{Type: lt, Verity: verity}, nil
fixed.

2025-02-19 06:29 UTC, rchincha commented on .github/workflows/coverage.yaml
> +          sudo apt-get install -y linux-modules-extra-$(uname -r)
Fixed.

2025-02-19 06:29 UTC, rchincha commented on .github/workflows/build.yaml
> +          sudo apt-get install -y linux-modules-extra-$(uname -r)
Fixed.

2025-02-19 13:13 UTC, raharper commented on cmd/stacker/build.go
> -			Name:  "no-squashfs-verity",
I think we need an cli alias here since users of stacker may be passing `--no-squashfs-verity`

2025-03-23 01:40 UTC, raharper approved these changes
Approved.

Started a cleanup request issue: https://github.com/project-stacker/stacker/issues/674

2025-03-23 01:41 UTC, merged

2025-03-23 04:26 UTC, rchincha commented
@hsiangkao https://github.com/project-stacker/stacker/releases/tag/v1.1.0-rc1 is now released with erofs support

```
stacker build --layer-type=erofs -f stacker.yaml
```

2025-03-23 11:56 UTC, hsiangkao commented
> @hsiangkao v1.1.0-rc1 is now released with erofs support
> 
> https://github.com/project-stacker/stacker/releases/download/v1.1.0-rc1/stacker
> 
> ```
> stacker build --layer-type=erofs -f stacker.yaml
> ```

That is a great news. currently there is an ongoing native erofs library, but it might need more time to get the full functionality.