temp: move to atomfs with fixed umount
project-stacker/stacker pull request #654
Opened 2024-12-19 00:50 UTC by mikemccracken

see https://github.com/project-machine/atomfs/pull/27

The MetadataPath field in the MountOCIOpts struct is not needed anymore, if left empty it will use /run/atomfs/ for all mounts.

The atomfs.bats file is not passing locally even though the equivalent test does pass in atomfs#27. Creating this PR to see if it passes in jenkins. It is something about the base image's verity device being in use. I suspect another test is not unmounting the shared base busybox image - maybe we need to isolate the tests better here, or just delete the atomfs test in stacker because it's covered in atomfs now

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-12-19 00:52 UTC, mikemccracken commented
Converted to draft because we shouldn't merge this, we should wait until atomfs merges atomfs#27 and then update to the main repo

2025-01-10 01:04 UTC, mikemccracken commented
this should work now but will need a change to the first commit to bring in the real atomfs repo once https://github.com/project-machine/atomfs/pull/27 is merged.

2025-01-15 00:24 UTC, raharper requested changes
Looks great!  Thank you for working through the CI.  Only change I think needed is ensuring we get the x/net bump to v0.33.0; I think you need 1.22.8 toolchain.  The rest are some questions.

2025-01-15 00:24 UTC, raharper commented on go.mod
> +	golang.org/x/net v0.25.0 // indirect
can we go ahead a bump to x/net to v0.33.0

2025-01-15 00:24 UTC, raharper commented on go.mod
> +toolchain go1.22.6
I think you need 1.22.8 for the x/net@v0.33.0 to fix the net cve

2025-01-15 00:24 UTC, raharper commented on test/atomfs.bats
> +    [ -b "/dev/mapper/$first_layer_hash-verity" ]
could you comment on what this fix is doing?

2025-01-15 00:24 UTC, raharper commented on test/bom.bats
> +    skip "second half of test requires running zot"
missing a tab? whitespace issue?

2025-01-15 00:24 UTC, raharper commented on test/bom.bats
> +  if [ -n "${ZOT_HOST}${ZOT_PORT}" ]; then
what's the reason for removing the colon? it seems strange to have both host and port in the string to check.

2025-01-15 00:28 UTC, mikemccracken commented on go.mod
> +toolchain go1.22.6
ah ok, I will update my tools and redo the go mod tidy, thanks

2025-01-15 00:34 UTC, mikemccracken commented on test/atomfs.bats
> +    [ -b "/dev/mapper/$first_layer_hash-verity" ]
sure - so, per the comment, the first layer should still exist since `a` is still mounted - line 104 and 105 put the hash of the first layer into `first_layer_hash`, and we should be checking ` [ -b "/dev/mapper/$first_layer_hash-verity" ]` to test that the verity block device for `first_layer_hash` still exists.

the earlier code was instead using an unassigned variable `$last_layer_hash`, which is set later in this test and in other tests, but at this point will be empty - so along with the `!`, we ended up checking that the block device `/dev/mapper/-verity` does NOT exist, which will be true, so the test passes but didn't test what it should. I assume this was just a typo.

this is the reason for the initial run of shellcheck I added, that specifically checks for the case where a variable is defined but in a separate subshell, which is what this turns into once you evaluate the bats magic:
https://github.com/project-stacker/stacker/pull/654/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R192

2025-01-15 00:38 UTC, mikemccracken commented on test/bom.bats
> +  if [ -n "${ZOT_HOST}${ZOT_PORT}" ]; then
shellcheck pointed out that using `-n` with a string that includes a literal string will never be false, because `[ -n ":" ]` is still true - so including the colon meant that we always try to do the zot stuff, even if there's no zot host/port configured.

I guess we could also just remove the port and only check `-n "$ZOT_HOST"`, if we wanted to support using a zot without an explicit port. This just seemed like the simplest change that fixed the issue

2025-01-15 00:40 UTC, mikemccracken commented on test/bom.bats
> +    skip "second half of test requires running zot"
hrm. looks like emacs shell-script mode's auto indent gets confused in bats files

2025-01-15 00:54 UTC, mikemccracken commented on go.mod
> +	golang.org/x/net v0.25.0 // indirect
done

2025-01-16 18:49 UTC, raharper commented on test/bom.bats
> +  if [ -n "${ZOT_HOST}${ZOT_PORT}" ]; then
sounds reasonable.  Thanks

2025-01-16 18:51 UTC, raharper approved these changes

2025-01-16 21:07 UTC, rchincha approved these changes
lgtm

2025-01-16 21:07 UTC, merged